### ISSUE TITLE
Solution file size limit?

### ISSUE THREAD

**Issue by lambeck** [CorterraSolutions/SolutionDependencyChecker#12]
I'm trying to check dependencies on a fairly large solution file (7305 KB). It's definitely a valid file, but I keep getting "File is invalid. Please check you loaded a valid solution file". Is there a size limit? Thanks!

**Comment by bonomo1** [comment]
@lambeck There should not be any limitations on size. I am fairly certain we tested solutions double the size of that.

Can you provide some more details (questions below)

1. Version of CRM, D365 CE, Dataverse the solution was built on?
2. Version of CRM, D365, CE, Dataverse for the target environment?
3. Types of components in the solution (entities, option sets, web resources etc.)
4. Does the file end in .zip?

**Comment by bonomo1** [comment]
Doesn't appear to be SVG icon as that is component type 61 of Web Resource.

Will have to dig into this more. Could be the "formulas" folder. Screenshot of solution that is failing for me as well

![image](https://user-images.githubusercontent.com/32522922/214892369-3d37ffb7-d73b-43b3-a24d-30309c62c960.png)

**Comment by lambeck** [comment]
Thanks for getting back to me!

Version of CRM, D365 CE, Dataverse the solution was built on?
Version of CRM, D365, CE, Dataverse for the target environment?
Our app uses some elements of D365 Project Operations (version 4.57.0.176), but most of it is custom. Both the source and destination environments have the same version.

Types of components in the solution (entities, option sets, web resources etc.)
The solution file includes:
- 1 Model Driven App
- 10 Custom Pages
- 21 Choices
- 3 Cloud Flows
- 2 Component Libraries
- 6 Connection References
- 2 PCF Controls
- 4 Duplicate Detection Rules
- 1 Environment variable
- 7 Security Roles
- 1 Site Map
- 32 Tables
- 17 Web Resources (javascript and images)

Does the file end in .zip? Yes. I've tried both managed and unmanaged.

I have a feeling that the problem might have to do with the Custom Pages :( Please let me know if you need any other information!

**Comment by bonomo1** [comment]
@lambeck Thank you for getting back to me. Will try my best to look into this as soon as I can and hope it's an easy fix. My fear is it will be a large overhaul based on changes in solutions that may take a couple of months to get prioritized on our end. I'll let you know one way or another soon.

**Comment by bonomo1** [comment]
Some news...created a blank solution and it threw the same error. No components at all. Not sure if that is good (i.e. quick fix) or bad (complete re-write)

![image](https://user-images.githubusercontent.com/32522922/214920267-defdcb87-c0bb-42e0-adfc-7a5029e49e3d.png)

**Comment by bonomo1** [comment]
Error on my end from the log file

> **. The import file is invalid. XSD validation failed with the following error: 'The element 'ImportExportXml' has invalid child element 'EntityDataProviders'.**  

Looks like its not handling virtual data sources in the solution file.

@lambeck 

Can you check the log file for the plugin? If you don't know where that is, you can find it under Configuration > Settings > Paths > Open XrmToolBox storage folder

![image](https://user-images.githubusercontent.com/32522922/214921879-2c832a86-1870-4cb9-b036-921186cecf45.png)

Then open the log file for the XRMSolutionDependencyChecker

![image](https://user-images.githubusercontent.com/32522922/214921990-d9c334b2-07f1-41ba-9405-1860ecb18bb9.png)

Assuming you get same error I am above

**Comment by bonomo1** [comment]
Temporary workaround. 

Unzip solution. Open customizations.xml

Remove note for "EntityDataProviders"

![image](https://user-images.githubusercontent.com/32522922/214923139-4b61c571-3c7c-4d78-816d-66e843919740.png)

Worked with a testing solution I had but so many components now your experience may differ. Solution was still importable on my end but use this workaround at your own risk until I can get an update out there

**Comment by bonomo1** [comment]
I should just have to update the references (note to myself more than anything) to target the latest and test to ensure still has backwards compatibility. 

```
  <package id="Microsoft.CrmSdk.CoreAssemblies" version="9.0.2.5" targetFramework="net462" />
  <package id="Microsoft.CrmSdk.Deployment" version="9.0.2.5" targetFramework="net462" />
  <package id="Microsoft.CrmSdk.Workflow" version="9.0.2.5" targetFramework="net462" />
```

**Comment by lambeck** [comment]
Sorry, no, same error :(

**Comment by bonomo1** [comment]
Quick update. My plan is to look further into this and hopefully resolve this weekend.

**Comment by bonomo1** [comment]
Apologies for the delay on this. Got busy with client work. Getting this into a team members queue to resolve soon hopefully

**Comment by lambeck** [comment]
No worries! Work is busy here too 🙂 Thanks for following up!
________________________________

**Comment by bonomo1** [comment]
Closing this issue for now
