### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by siggipop** [CorterraSolutions/SolutionDependencyChecker#13]
label: question 
How does this tool work? Does it use standard PAC CLI method or does it query components directly with OragnisationService? 
How can this be implemented in a DevOps cycle?

**Comment by bonomo1** [comment]
Uses the RetrieveMissingComponentsRequest

https://learn.microsoft.com/en-us/dotnet/api/microsoft.crm.sdk.messages.retrievemissingcomponentsrequest?view=dataverse-sdk-latest
