### ISSUE TITLE
Tool does not work anymore

### ISSUE THREAD

**Issue by jsteffen76** [CorterraSolutions/SolutionDependencyChecker#18]
**Describe the bug**
The tool keep stating it us unable to find missing components. When we attempt to import into org, it fails due to dependencies.

**To Reproduce**
1. Go to 'Solution Dependency Checker" tool
2. Click on 'open solution' and select the solution
3. States" Unable to find missing components" in any environment even if the solution came from another tenant

**Expected behavior**
Expected to show all dependencies that are missing with output file

**Screenshots**
![image](https://github.com/CorterraSolutions/SolutionDependencyChecker/assets/32177172/8dff79fb-79bd-4408-8714-b566ff79c464)

**Desktop (please complete the following information):**

**XRM Toolbox Version:**
Version: was on an older version and just updated to the newest version - same results

**Comment by bonomo1** [comment]
Thank you for reporting this.  

Can you clarify a few things
1. It was working fine until you updated to a new version of XRM Toolbox itself? What version was it working on and what version are you on now?
2. What version of the Solution Dependency Checker plugin are you using, the latest or older version?
3. What OS are you running?
4. Is your solution targeting on premises or the Power Platform/Dataverse?
5. Is the solution from a first party Microsoft app (Sales, Proj Ops, etc. ) or only contain customizations from a Power Platform environment?

**Comment by jsteffen76** [comment]
Hi Joe,

I haven't used the solution checker in a few months but it was working before. I just updated the solution and XRM Toolbox to the latest versions available and I am not sure what version I was on before that.
My OS version is below
***@***.***
We are targeting an online version of Dynamics
The solution contains customizations we created as a patch in a dev environment and we can't import into our qa/prod environments due to dependency issues.

Thanks!




Jackie Steffen | Technical Services Representative | Beringer Technology Group | www.beringer.net
Tel: 
856-325-2800 | Email: ***@***.***
IT Outsourcing | CRM Solutions  | CRM for Distribution | VoIP | Backup & Recovery | Cloud Computing

**Comment by bonomo1** [comment]
Thank you for the information. I wonder if patches are not working anymore for some reason. Have you used this with a patch solution before to you knowledge?

**Comment by jsteffen76** [comment]
Yes, that's what I had used it for previously as we had a similar issue.




Jackie Steffen | Technical Services Representative | Beringer Technology Group | www.beringer.net
Tel: 
856-325-2800 | Email: ***@***.***
IT Outsourcing | CRM Solutions  | CRM for Distribution | VoIP | Backup & Recovery | Cloud Computing

**Comment by bonomo1** [comment]
Thanks for clarifying. I'll look into what may be going on.

Joe Bonomo | Cell: 6302540645 | Email: ***@***.***
________________________________

**Comment by jsteffen76** [comment]
Hi Joe,

I am just checking in on this to see if you were able to figure out what is going on.

Thanks!




Jackie Steffen | Technical Services Representative | Beringer Technology Group | www.beringer.net
Tel: 
856-325-2800 | Email: ***@***.***
IT Outsourcing | CRM Solutions  | CRM for Distribution | VoIP | Backup & Recovery | Cloud Computing

**Comment by bonomo1** [comment]
I've taken a look and I have been unable to repeat this result in any of the environments I have access to internally or at our clients. For some reason it is not receiving an object of missing components but just a generic object.

Two things I may ask of you:
1. **Log file**. Can you go to the log file and send me the results? You can get to this by going to Settings > Paths. Open the "storage" folder and then find the local for the XRMSolutionDependencyChecker. We put more logs in here than what is shown in XRMToolbox istelf.

![image](https://github.com/CorterraSolutions/SolutionDependencyChecker/assets/32522922/edcd1096-8d33-4a43-8e80-f84013ee22a7)
![image](https://github.com/CorterraSolutions/SolutionDependencyChecker/assets/32522922/e9616fdd-68a5-411a-a1db-d6ec886611d2)


2. **Solution share?**. I have to ask but I'm sure I know the answer, could you share the solution with me so I can debug with your solution? In a past issue, someone was getting the failure regardless of the components they included and shared a "small" solution which helped identify the issue

**Comment by jsteffen76** [comment]
Hi Joe,

Sorry for the delay. I am discussing this with the rest of our development team to see if anyone else has used the tool recently. We were able to remove all the dependencies through the failed log file from Microsoft so we can't reproduce the issue with that solution.

Thanks!




Jackie Steffen | Technical Services Representative | Beringer Technology Group | www.beringer.net
Tel: 
856-325-2800 | Email: ***@***.***
IT Outsourcing | CRM Solutions  | CRM for Distribution | VoIP | Backup & Recovery | Cloud Computing

**Comment by bonomo1** [comment]
Thanks, ill close this issue then

**Comment by jsteffen76** [comment]
Hi Joe,

I am adding our implementation specialist onto this ticket because he was able to recreate the issue with another solution. Did you want to do a call to review it or just have him send the solution somehow?

Thanks!




Jackie Steffen | Technical Services Representative | Beringer Technology Group | www.beringer.net
Tel: 
856-325-2800 | Email: ***@***.***
IT Outsourcing | CRM Solutions  | CRM for Distribution | VoIP | Backup & Recovery | Cloud Computing

**Comment by bonomo1** [comment]
I've continued to look into the issue. From what I've gathered the error is showing on requesting the missing components. Another person reported the same issue through another channel. They repeated the issue by creating a flow on a new entity and removing the entity from the solution. I did the same tonight in a test yet had no issues, it correctly reported the missing component being the entity.  Still confusing why it's working in all my testing but not working in a couple examples (multiple versions of XRM Toolbox, multiple versions of CE/XRM/Dataverse, managed and unmanaged solutions, etc.)

Detailed error from log:
`
System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: An unexpected error occurred. (Fault Detail is equal to Exception details: 
ErrorCode: 0x80040216
Message: An unexpected error occurred.
TimeStamp: 2023-11-02T15:30:14.5244690Z
--
Exception details: 
ErrorCode: 0x80040216
Message: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal) +0x5c
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info) +0x20
   at Microsoft.Crm.Tools.ImportExportPublish.ImportXml.RetrieveMissingComponents() +0x0
   at Microsoft.Crm.WebServices.ImportXmlService.RetrieveMissingComponents(Byte[] customizationXml, ExecutionContext context) +0x25: Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #2DBDEFE9
TimeStamp: 2023-11-02T15:30:14.5244690Z
--
).
`

**Test Case**
![image](https://github.com/CorterraSolutions/SolutionDependencyChecker/assets/32522922/c8463ea1-c0a1-4920-9984-255c961de92f)

**Comment by bonomo1** [comment]
After a few weeks of troubleshooting, the conclusion at this time seems to be the error is a bug in the Microsoft API. The original reporter of the issue and another individual have successfully used the tool numerous times since the initial issue was reported.
